name: App Styles / Format
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: App Install dependencies
        working-directory: ./template
        run: npm install
      - name: App Stylelint
        working-directory: ./template
        run: npm run stylelint
      - name: App Format Check
        working-directory: ./template
        run: npm run format:check
